version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    allow:
      - dependency-type: "all"
